name       : python-bidict
version    : 0.21.4
release    : 1
source     :
    - https://pypi.io/packages/source/b/bidict/bidict-0.21.4.tar.gz : 42c84ffbe6f8de898af6073b4be9ea7ccedcd78d3474aa844c54e49d5a079f6f
license    : MPL-2.0
component  : programming.python
summary    : The bidirectional mapping library for Python.
description: |
    Bidirectional mapping library that works out-of-the-box with Python's standard library and native integration with collections.abc.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
